# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
  - name: Gemini 2.5 Pro
    provider: gemini
    model: gemini-2.5-pro-latest
    apiKey: TU_NUEVA_API_KEY_DE_GOOGLE

  - name: Gemini 2.5 Flash
    provider: gemini
    model: gemini-2.5-flash-latest
    apiKey: TU_NUEVA_API_KEY_DE_GOOGLE

  - name: DeepSeek R1 8B (Local)
    provider: ollama
    model: deepseek-r1:8b

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp